In [17]:
#importing required libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn  import metrics
import seaborn as sns
from sklearn.decomposition import PCA

In [4]:
taxi_df=sns.load_dataset('taxis')
taxi_df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan


In [5]:
taxi_df.describe()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total
count,6433,6433,6433.000000,6433.000000,6433.000000,6433.00000,6433.000000,6433.000000
mean,2019-03-16 08:31:28.514223616,2019-03-16 08:45:49.491217408,1.539251,3.024617,13.091073,1.97922,0.325273,18.517794
min,2019-02-28 23:29:03,2019-02-28 23:32:35,0.000000,0.000000,1.000000,0.00000,0.000000,1.300000
25%,2019-03-08 15:50:34,2019-03-08 16:12:51,1.000000,0.980000,6.500000,0.00000,0.000000,10.800000
50%,2019-03-15 21:46:58,2019-03-15 22:06:44,1.000000,1.640000,9.500000,1.70000,0.000000,14.160000
75%,2019-03-23 17:41:38,2019-03-23 17:51:56,2.000000,3.210000,15.000000,2.80000,0.000000,20.300000
max,2019-03-31 23:43:45,2019-04-01 00:13:58,6.000000,36.700000,150.000000,33.20000,24.020000,174.820000
std,NaN,NaN,1.203768,3.827867,11.551804,2.44856,1.415267,13.815570


In [6]:
taxi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64         
 3   distance         6433 non-null   float64       
 4   fare             6433 non-null   float64       
 5   tip              6433 non-null   float64       
 6   tolls            6433 non-null   float64       
 7   total            6433 non-null   float64       
 8   color            6433 non-null   object        
 9   payment          6389 non-null   object        
 10  pickup_zone      6407 non-null   object        
 11  dropoff_zone     6388 non-null   object        
 12  pickup_borough   6407 non-null   object        
 13  dropoff_borough  6388 non-null   object        
dtypes: datetime64[ns](2), float64(5), int64(

In [7]:
taxi_df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [8]:
df=taxi_df.dropna()

In [9]:
le=LabelEncoder()
taxi_df['payment']=le.fit_transform(taxi_df['payment'])

In [10]:
x=taxi_df[['fare', 'distance', 'pickup_borough', 'dropoff_borough']]
x=pd.get_dummies(x,drop_first=True)

In [11]:
y=taxi_df['payment']


In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [14]:
clf=RandomForestClassifier(n_estimators=100,random_state=42)
clf.fit(x_train_scaled,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [15]:
y_pred=clf.predict(x_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.6472416472416472


In [18]:
pca=PCA(n_components=2)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)

In [19]:
clf_pca=RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [20]:
y_pred_pca2=clf_pca.predict(x_test_pca)
print("Accuracy with PCA:",metrics.accuracy_score(y_test,y_pred_pca2))

Accuracy with PCA: 0.6324786324786325


In [21]:
pca=PCA(n_components=3)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)

In [23]:
clf_pca=RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [25]:
y_pred_pca3=clf_pca3.predict(x_test_pca)
print("Accuracy with PCA (3 components):",metrics.accuracy_score(y_test,y_pred_pca3))

Accuracy with PCA (3 components): 0.6456876456876457


In [27]:
pca=PCA(n_components=4)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)

In [28]:
clf_pca=RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [29]:
y_pred_pca4=clf_pca.predict(x_test_pca)
print("Accuracy with PCA (4 components):",metrics.accuracy_score(y_test,y_pred_pca4))

Accuracy with PCA (4 components): 0.634032634032634


In [26]:
#print accuracy of all pca's respectively
print("Accuracy without PCA:",metrics.accuracy_score(y_test,y_pred))
print("Accuracy with PCA (2 components):",metrics.accuracy_score(y_test,y_pred_pca2))
print("Accuracy with PCA (3 components):",metrics.accuracy_score(y_test,y_pred_pca3))

Accuracy without PCA: 0.6472416472416472
Accuracy with PCA (2 components): 0.6324786324786325
Accuracy with PCA (3 components): 0.6456876456876457


PCA on iris dataset


In [ ]:
#loading the required libraries
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [2]:
iris_df=sns.load_dataset('iris')
iris_df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [3]:
iris_df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [4]:
iris_df.shape

(150, 5)

In [5]:
iris_df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
df=iris_df.dropna()

In [9]:
x=iris_df.drop(columns=['species'])
y=iris_df['species']

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
print("Training set shape:",x_train.shape)
print("Testing set shape:",x_test.shape)

Training set shape: (120, 4)
Testing set shape: (30, 4)


In [13]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
print(x_train_scaled)
print(x_test_scaled)

[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.72969227  0.95664273]
 [ 0.72020757  0.30929911  0.44316389  0.4227026 ]
 [-0.74255534  0.98006827 -1.27600637 -1.31260282]
 [-0.98634915  1.20365799 -1.33331205 -1.31260282]
 [-0.74255534  2.32160658 -1.27600637 -1.44608785]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993  0.75647855  0.44316389  0.55618763]
 [ 1.08589829  0.08570939  0.55777524  0.4227026 ]
 [-0.49876152  1.87442714 -1.39061772 -1.04563275]
 [-0.49876152  1.4272477  -1.27600637 -1.31260282]
 [-0.37686461 -1.47941864 -0.01528151 -0.24472256]
 [ 0.59831066 -0.58505976  0.78699794  0.4227026 ]
 [ 0.72020757  0.08570939  1.01622064  0.8231577 ]
 [ 0.96400139 -0.13788033  0.38585821  0.28921757]
 [ 1.69538284  1.20365799  1.36

In [14]:
clf=RandomForestClassifier(n_estimators=100,random_state=42)
clf.fit(x_train_scaled,y_train)
y_pred=clf.predict(x_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 1.0


In [15]:
pca=PCA(n_components=2)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)

In [16]:
clf_pca=RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca.fit(x_train_pca,y_train)
y_pred_pca2=clf_pca.predict(x_test_pca)
print("Accuracy with PCA (2 components):",metrics.accuracy_score(y_test,y_pred_pca2))

Accuracy with PCA (2 components): 0.9


In [17]:
pca=PCA(n_components=3)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)
clf_pca3=RandomForestClassifier(n_estimators=100,random_state=42)
clf_pca3.fit(x_train_pca,y_train)
y_pred_pca3=clf_pca3.predict(x_test_pca)
print("Accuracy with PCA (3 components):",metrics.accuracy_score(y_test,y_pred_pca3))

Accuracy with PCA (3 components): 1.0


In [18]:
print("Accuracy's of all: \n")
print("Accuracy on Raw Data:",metrics.accuracy_score(y_test,y_pred))
print("Accuracy with PCA (2 components):",metrics.accuracy_score(y_test,y_pred_pca2))
print("Accuracy with PCA (3 components):",metrics.accuracy_score(y_test,y_pred_pca3))

Accuracy's of all: 

Accuracy on Raw Data: 1.0
Accuracy with PCA (2 components): 0.9
Accuracy with PCA (3 components): 1.0
